### ISSUE TITLE
Errors on defaults tab

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/userprotect#1]
![Screenshot from 2020-08-21 14-30-10](https://user-images.githubusercontent.com/1071483/90922960-d8dce980-e3ba-11ea-9dd0-e0d0ae590d1a.png)

I see this error right after installing on a fresh site. I haven't changed any settings. I haven't dug in further.

**Comment by herbdool** [comment]
The userprotect.settings.json file is not correct.

**Comment by laryn** [comment]
Ah, good catch. Forgot to clean that up after Coder Upgrade created it...

**Comment by herbdool** [comment]
@laryn I created a PR

**Comment by herbdool** [comment]
I think there's also an issue with the release. It doesn't look right in github, just says "tag". And drush can't download it.

**Comment by herbdool** [comment]
Looks like .install also needs updating. I'll add that.

**Comment by laryn** [comment]
> I think there's also an issue with the release.

Maybe because I checked the box that said "Pre-release"? Just guessing. I knew it wasn't completely tested yet...

**Comment by herbdool** [comment]
I've also updated the .install - needed proper defaults and was missing `$config->save()` (is this because coder upgrade is missing it?). And fixed the `hook_config_info()`

**Comment by laryn** [comment]
Thanks @herbdool ! Yes, that looks like what was spit out by Coder Upgrade. Been meaning to file an issue about some of those so they don't happen every time. Clearly I didn't walk through the clean up phase in as much depth as usual on this one...

**Comment by laryn** [comment]
Looks like you found some of them before, too: https://github.com/backdrop-contrib/coder_upgrade/issues/26

**Comment by herbdool** [comment]
I tend not to use coder_upgrade since it's easy to miss things that still need to be fixed.

**Comment by herbdool** [comment]
I've tested the PR locally so I think it's working.

**Comment by laryn** [comment]
@herbdool thanks! Looks great and since there was no formal release yet I've merged without testing. If you're about to use/test further please let me know of any other bugs you may find. If it's running well for you I'll make a new release.

**Comment by herbdool** [comment]
sounds good. I tested it on a client site. So far I'm not sure it's working properly - it's not blocking a user from actually changing fields - so I'll have to test again locally. Maybe I don't understand how it works.

**Comment by laryn** [comment]
The interface is a little strange for sure. I haven't even thought about improving that yet, just trying to get parity first. :)

(I'm not using it on Backdrop yet but will be in the future when a D7 site I support gets updated.)

**Comment by herbdool** [comment]
I read the wiki - so I think it is working correctly. However, not as I expected. I think I'm only interested in the permissions the module provides - want to prevent a role from editing their own accounts. (I had advised our client not to go this route, but, sigh, ...)

**Comment by laryn** [comment]
> (I had advised our client not to go this route, but, sigh, ...)

I certainly know that feeling.

**Comment by laryn** [comment]
@herbdool What do you think of the UI in these screenshots?
https://github.com/backdrop-contrib/userprotect/issues/3

**Comment by herbdool** [comment]
I like them. Though now my client won't be using them. I convinced them to take a different approach, using Backdrop and CiviCRM.
